config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :clubs
  root 'pages#home'
  resources :clubs do
    resources :comments, only: [:create, :destroy]
  end
  get '/profile', to: 'pages#profile'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/club.rb
class Club < ApplicationRecord
  has_one_attached :photo

  validates :address, presence: true
  validate :address_in_france

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :creator, class_name: "User", foreign_key: "creator_id", optional: true
  has_many :club_edits, dependent: :destroy
  has_many :editors, through: :club_edits, source: :user
  has_many :comments, dependent: :destroy

  def average_rating
    total_notes = comments.sum(:note)
    total_comments = comments.count
    return 0 if total_comments.zero?
    total_notes.to_f / total_comments
  end

  private

  def address_in_france
    if address.present? && !photo.attached?
      result = Geocoder.search(address).first
      unless result && result.country == "France"
        errors.add(:address, "doit être en France")
      end
    end
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ show index ]

  # GET /clubs or /clubs.json
  def index
    @clubs = Club.all

    @clubs_with_region = Club.all.map do |club|
      location = Geocoder.search([club.latitude, club.longitude]).first
      if location.present? && location.data["address"].present?
        region_code = location.data["address"]["ISO3166-2-lvl6"] || location.data["address"]["ISO3166-2-lvl6"]
        region_code_digits = region_code.scan(/\d/).join
        { club: club, region_code: region_code_digits }
      end
    end.compact

    # Trie les clubs par code de région
    @sorted_clubs = @clubs_with_region.sort_by { |club_info| club_info[:region_code] }

  end

  # GET /clubs/1 or /clubs/1.json
  def show
    @club = Club.find(params[:id]) # Récupère le club spécifique
    @comments = @club.comments # Récupère les commentaires associés à ce club

  end


  # GET /clubs/new
  def new
    @club = current_user.created_clubs.build
  end

  # GET /clubs/1/edit
  def edit
  end

  # POST /clubs or /clubs.json
  def create
    @club = Club.new(club_params)
    @club.creator = current_user # Définir le créateur comme l'utilisateur actuel

    respond_to do |format|
      if @club.save
        format.html { redirect_to club_url(@club), notice: "Le club a été créé avec succès." }
        format.json { render :show, status: :created, location: @club }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /clubs/1 or /clubs/1.json
  def update
    respond_to do |format|
      if @club.update(club_params)
        # Vérifier si l'utilisateur actuel n'est pas déjà un éditeur du club
        unless @club.editors.include?(current_user)
          # Ajouter l'utilisateur actuel à la liste des éditeurs du club
          @club.editors << current_user
        end

        format.html { redirect_to club_url(@club), notice: "Le club a été mis à jour avec succès." }
        format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /clubs/1 or /clubs/1.json
  def destroy
    @club = Club.find(params[:id])
    if @club.destroy
      respond_to do |format|
        format.html { redirect_to profile_path, notice: "Le club a été supprimé avec succès." }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to profile_path, alert: "Erreur lors de la suppression du club." }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def club_params
      params.require(:club).permit(:name, :city, :description, :address, :photo)
    end


end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/views/clubs/_club.html.erb
<div id="<%= dom_id club %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Nom :</strong>
    <%= club.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Adresse :</strong>
    <%= club.address %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description :</strong>
    <%= club.description %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Voir ce club", club, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Modifier ce club", edit_club_path(club), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/clubs/_form.html.erb
<%= simple_form_for club, html: { class: "contents" } do |form| %>
  <% if club.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(club.errors.count, "erreur") %> a empêché l'enregistrement de ce club:</h2>

      <ul>
        <% club.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.input :name, label: "Nom", input_html: { class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" } %>
  </div>

  <div class="complete shadow rounded-md border border-gray-200 outline-none mt-2 w-full">
    <%= form.input :address,
        label: false,
        input_html: { id: "query_address", data: { address_autocomplete_target: "address", geoloc_target: "address" }, class: "hidden" },
        wrapper_html: { data: { controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"], geoloc_target: "addressWrapper" },  }
      %>
  </div>


  <div class="my-5">
    <%= form.input :description, label: "Description", as: :text, input_html: { rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" } %>
  </div>

  <div class="my-5">
    <%= form.input :photo, label: "Photo", as: :file, input_html: { class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" } %>
  </div>

  <div class="inline">
    <%= form.button :submit, "Enregistrer", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/clubs/edit.html.erb
<div class="mx-auto w-4/5 ">
  <h1 class="font-bold text-4xl">Modifier ce club</h1>

  <%= render "form", club: @club %>

  <%= link_to "Voir ce club", @club, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
<%= link_to "Retour aux clubs", clubs_path, class: "lg:ml-2 lg:mb-0 mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/clubs/index.html.erb
<div class="w-11/12 shadow-md rounded-md overflow-hidden mx-auto mt-16 ">
  <div class="bg-gray-100 py-2 px-4">
    <h2 class="text-xl font-semibold text-gray-800">Tous les clubs</h2>
  </div>
  <ul class="divide-y divide-gray-200">
    <% @sorted_clubs.each do |club_info| %>
      <% club = club_info[:club] %>
      <li id="<%= dom_id club %>" class="flex items-center py-4 px-6">
        <span class="text-gray-700 text-lg font-medium mr-4"><%= club_info[:region_code] %></span>
        <% if club.photo.attached? %>
          <%= cl_image_tag club.photo.key, height: 300, width: 400, crop: :fill, class: "w-12 h-12 rounded-full object-cover mr-4" %>
        <% else %>
          <img class="w-12 h-12 rounded-full object-cover mr-4" src="https://c7.alamy.com/compfr/2eawdy4/armes-a-feu-logo-quatre-votre-entreprise-2eawdy4.jpg" alt="User avatar">
        <% end %>

        <div class="flex-1">
          <h3 class="text-lg font-medium text-gray-800"><%= club.name %></h3>
          <p class="text-gray-600 text-base w-20 sm:w-full" style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">
            <%= club.address %>
          </p>
          <%= link_to "Voir ce club", club, class: "rounded-lg p-2 bg-gray-100 inline-block font-medium" %>
        </div>
        <div>
          <% if club.comments.any? %>
            <p class="ml-2 flex items-center">
              <%= club.average_rating.round(1) %>
              <svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" viewBox="0 0 24 24" fill="currentColor" class="icon icon-tabler icons-tabler-filled icon-tabler-star text-yellow-400">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                <path d="M8.243 7.34l-6.38 .925l-.113 .023a1 1 0 0 0 -.44 1.684l4.622 4.499l-1.09 6.355l-.013 .11a1 1 0 0 0 1.464 .944l5.706 -3l5.693 3l.1 .046a1 1 0 0 0 1.352 -1.1l-1.091 -6.355l4.624 -4.5l.078 -.085a1 1 0 0 0 -.633 -1.62l-6.38 -.926l-2.852 -5.78a1 1 0 0 0 -1.794 0l-2.853 5.78z" />
              </svg>
              (<%= club.comments.count %>)
            </p>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/clubs/new.html.erb
<div class="mx-auto w-4/5" data-controller="address-autocomplete">
  <h1 class="font-bold text-4xl">Nouveau club</h1>

  <%= render "form", club: @club %>

  <%= link_to "Retour aux clubs", clubs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/clubs/show.html.erb
<div class="mx-auto  flex" data-controller="club-show" >
  <div class="mx-auto w-full">
    <section class="slider-wrapper" data-controller="slider">
      <button class="slide-arrow" id="slide-arrow-prev">&#8249;</button>
      <button class="slide-arrow" id="slide-arrow-next">&#8250;</button>
      <ul class="slides-container" id="slides-container">
        <% if @comments.any? { |comment| comment.photo.present? } %>
          <% @comments.shuffle.each do |comment| %>
            <% if comment.photo.attached? %>
              <li class="slide" style="display: flex; justify-content: center; align-items: center;">
                <%= cl_image_tag comment.photo.key %>
              </li>
            <% end %>
          <% end %>
        <% else %>
          <li class="slide" style="display: flex; justify-content: center; align-items: center;">
            <%= image_tag 'no_picture.png' %>
          </li>
        <% end %>
      </ul>
    </section>


    <div data-controller="down-page" class="py-4 px-6 div">
      <div class="flex items-center justify-between relative">
        <div class="flex items-center">
          <% if @club.photo.attached? %>
            <%= cl_image_tag @club.photo.key, height: 300, width: 400, crop: :fill, class: "w-12 h-12 rounded-full object-cover mr-4" %>
          <% else %>
            <img class="w-12 h-12 rounded-full object-cover mr-4" src="https://c7.alamy.com/compfr/2eawdy4/armes-a-feu-logo-quatre-votre-entreprise-2eawdy4.jpg" alt="User avatar">
          <% end %>
          <h3 class="text-lg font-medium text-gray-800 flex items-center">
            <%= @club.name.titleize %>
          </h3>
          <% if @club.comments.any? %>
            <p class="ml-2 flex items-center">
              <%= @club.average_rating.round(1) %>
              <svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" viewBox="0 0 24 24" fill="currentColor" class="icon icon-tabler icons-tabler-filled icon-tabler-star text-yellow-400">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                <path d="M8.243 7.34l-6.38 .925l-.113 .023a1 1 0 0 0 -.44 1.684l4.622 4.499l-1.09 6.355l-.013 .11a1 1 0 0 0 1.464 .944l5.706 -3l5.693 3l.1 .046a1 1 0 0 0 1.352 -1.1l-1.091 -6.355l4.624 -4.5l.078 -.085a1 1 0 0 0 -.633 -1.62l-6.38 -.926l-2.852 -5.78a1 1 0 0 0 -1.794 0l-2.853 5.78z" />
              </svg>
              (<%= @club.comments.count %>)
            </p>
          <% end %>
        </div>

        <div>
          <div id="dropdown">
            <div data-controller="dropdown" class="relative">
              <button type="button" data-action="dropdown#toggle click@window->dropdown#hide" class="flex items-center border border-gray-200 rounded shadow-md p-1">
                <span>
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-caret-down">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <path d="M6 10l6 6l6 -6h-12" />
                  </svg>
                </span>
                <span>
                  <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-settings" width="18" height="18" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" />
                    <path d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 0 0 2.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 0 0 1.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 0 0 -1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 0 0 -2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 0 0 -2.573 -1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 0 0 -1.065 -2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 0 0 1.066 -2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
                    <circle cx="12" cy="12" r="3" />
                  </svg>
                </span>
              </button>

              <div
                data-dropdown-target="menu"
                class="absolute z-50 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 right-0"
                data-transition-enter-from="opacity-0 scale-95"
                data-transition-enter-to="opacity-100 scale-100"
                data-transition-leave-from="opacity-100 scale-100"
                data-transition-leave-to="opacity-0 scale-95"
                style="top: 2.5rem;"
              >
                <% if user_signed_in? %>
                  <%= link_to "Modifier ce club", edit_club_path(@club), class: "block px-4 py-2 text-center hover:bg-gray-100 rounded-t-lg" %>
                <% else %>
                  <%= link_to 'Modifier ce club', user_session_path, class: "block px-4 py-2 text-center hover:bg-gray-100" %>
                <% end %>
                <% if user_signed_in? && current_user == @club.creator %>
                  <%= form_with(method: :delete, url: club_path(@club), class: "delete-alertbox d-none", data: { controller: "delete-confirmation" }) do |form| %>
                    <%= form.submit "Delete", class: "block w-full px-4 py-2 hover:bg-red-300 rounded-b-lg" %>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>

      </div>

      <p class="mt-2 text-gray-600 text-base"><%= @club.address %></p>
      <a href="<%= "https://www.google.com/maps/search/?api=1&query=#{@club.latitude},#{@club.longitude}" %>" class="block text-blue-500 mb-2" target="_blank">Voir sur Google Maps</a>
      <div class="bg-white shadow-md rounded-md p-6 mb-8">
        <p class="text-gray-600 text-base"><%= @club.description %></p>
      </div>


      <button data-action="click->club-show#toggleCommentForm click->down-page#scrollDown" class="mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium flex justify-center">Ajouter un commentaire</button>

      <div id="comment-form-container" class="hidden" data-down-page-target="commentFormContainer">
        <% if user_signed_in? %>
          <%= form_with(model: [@club, @club.comments.build], url: club_comments_path(@club), method: :post) do |form| %>
            <div class="field">
              <%= form.label :description, class: "block my-2 text-sm font-medium text-gray-900" %>
              <%= form.text_area :description, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5", rows: 4, required: true %>
            </div>

            <div class="field">
              <%= form.label :photo, class: "block my-2 text-sm font-medium text-gray-900" %>
              <%= form.file_field :photo, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5" %>
            </div>

            <div class="field">
              <%= form.label :note, class: "block my-2 text-sm font-medium text-gray-900" %>
              <div class="flex items-center">
                <% (1..5).each do |i| %>
                  <%= form.radio_button :note, i, class: "rating-star", id: "note_#{i}" %>
                  <label class="rating-star-label" for="note_<%= i %>">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" class="icon icon-tabler icons-tabler-filled icon-tabler-star">
                      <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                      <path d="M8.243 7.34l-6.38 .925l-.113 .023a1 1 0 0 0 -.44 1.684l4.622 4.499l-1.09 6.355l-.013 .11a1 1 0 0 0 1.464 .944l5.706 -3l5.693 3l.1 .046a1 1 0 0 0 1.352 -1.1l-1.091 -6.355l4.624 -4.5l.078 -.085a1 1 0 0 0 -.633 -1.62l-6.38 -.926l-2.852 -5.78a1 1 0 0 0 -1.794 0l-2.853 5.78z" />
                    </svg>
                  </label>
                <% end %>
              </div>
            </div>

            <div class="actions mx-auto w-2/5 mt-2 bg-gray-100 rounded hover:bg-gray-300 cursor-pointer">
              <%= form.submit "Commenter", class: "text-black w-full  focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center" %>
            </div>
          <% end %>
        <% else %>
          <p><%= link_to 'Connectez-vous', user_session_path, class: "text-blue-500 hover:text-blue-600 hover:underline cursor-pointer" %> pour ajouter un commentaire.</p>
        <% end %>
      </div>


      <div class="mt-4">
        <% if @comments.present? %>
          <h3 class="font-bold text-lg text-gray-800">Commentaires : (<%= @comments.count %>)</h3>
          <% @comments.each do |comment| %>
            <% if comment.description.present? %>
              <div class="bg-gray-200 rounded-lg p-3 mt-2">
                <p class="text-sm text-gray-600 "><%= comment.user.name %></p>
                <p class="text-gray-800"><%= comment.description %></p>
                <% if comment.note? && comment.note > 0 %>
                  <span>
                    <p class="flex items-center text-gray-600">note:
                      <% comment.note.times do %>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" class="icon icon-tabler icons-tabler-filled icon-tabler-star">
                          <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                          <path d="M8.243 7.34l-6.38 .925l-.113 .023a1 1 0 0 0 -.44 1.684l4.622 4.499l-1.09 6.355l-.013 .11a1 1 0 0 0 1.464 .944l5.706 -3l5.693 3l.1 .046a1 1 0 0 0 1.352 -1.1l-1.091 -6.355l4.624 -4.5l.078 -.085a1 1 0 0 0 -.633 -1.62l-6.38 -.926l-2.852 -5.78a1 1 0 0 0 -1.794 0l-2.853 5.78z" />
                        </svg>
                      <% end %>
                    </p>
                  </span>
                <% end %>
              </div>
            <% end %>
          <% end %>
        <% else %>
          <h3 class="font-bold text-lg text-gray-800">Pas de Commentaires :</h3>
        <% end %>
      </div>
      <div class="mt-4 mb-8">
        <h3 class="text-lg font-medium text-gray-800">Personne ayant modifié ou créé le club :</h3>
        <h4 class="font-medium text-gray-800">Créateur : <%= @club.creator.present? ? @club.creator.name : "Inconnu" %></h4>
        <p class="text-gray-600 text-base opacity-75">Éditeurs :</p>
        <ul class="list-disc ml-4 text-gray-600 opacity-75">
          <% @club.editors.each do |editor| %>
            <li><%= editor.name %></li>
          <% end %>
        </ul>
      </div>

    </div>
  </div>
</div>